import type { Metadata } from "next";
import { Milonga } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const font = Milonga({
  subsets: ["latin"], 
  weight: "400",
});

export const metadata: Metadata = {
  title: "NIGELLA || Pimple Cream",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <NavBar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
